spin_manifest_version = "1"
authors = ["Ilkka Poutanen <ilkka@ilkka.dev>"]
description = ""
name = "spin-helloworld"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-helloworld"
source = "target/wasm32-wasi/release/spin_helloworld.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
